import {roleContent,esc} from './careers-job-shared.mjs';
const $=selector=>document.querySelector(selector);
const allowedReviewHost=/(^|\.)(githack\.com|shipstatic\.com)$/.test(location.hostname)||['localhost','127.0.0.1'].includes(location.hostname);
const demo=document.body.dataset.reviewDemo==='true'&&allowedReviewHost;
let user=null,jobs=[],selected=null,csrf='',dirty=false,busy=false;
const editor=$('#hr-editor');
const fieldNames=[...editor.querySelectorAll('[name]')].map(n=>n.name);
function message(text,error=false){$('#hr-editor-status').textContent=text;$('#hr-editor-status').dataset.error=String(error);}
function formData(){return Object.fromEntries(fieldNames.map(key=>[key,editor.elements[key].value.trim()]));}
function gate(){editor.querySelectorAll('button').forEach(b=>b.disabled=busy);$('#hr-publish').disabled=busy||!selected||dirty||user?.role!=='publisher';$('#hr-close').disabled=busy||selected?.status!=='published'||user?.role!=='publisher';$('#hr-duplicate').disabled=busy||!selected;$('#hr-dirty').hidden=!dirty;}
function changed(){dirty=true;$('#hr-approval').checked=false;gate();}
editor.addEventListener('input',e=>{if(e.target.id!=='hr-approval')changed();});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
function canLeave(){return !dirty||confirm('Discard the unsaved changes to this draft?');}
function renderList(){const q=$('#hr-search').value.toLowerCase(),filter=$('#hr-filter').value;const result=jobs.filter(j=>(!filter||j.status===filter)&&`${j.draft.title} ${j.id}`.toLowerCase().includes(q));$('#hr-count').textContent=`${result.length} ${result.length===1?'role':'roles'}`;$('#hr-job-list').innerHTML=result.map(j=>`<button type="button" class="hr-jobButton" data-job-id="${esc(j.id)}" aria-current="${selected?.id===j.id}"><b>${esc(j.draft.title)}</b><span>${esc(j.status.toUpperCase())} · V${j.version}${j.status==='published'&&j.version!==j.live?.liveVersion?' · draft changes':''}</span></button>`).join('')||'<p>No matching roles.</p>';}
$('#hr-search').addEventListener('input',renderList);$('#hr-filter').addEventListener('change',renderList);
$('#hr-job-list').addEventListener('click',e=>{const b=e.target.closest('[data-job-id]');if(b&&canLeave())select(jobs.find(j=>j.id===b.dataset.jobId));});
async function api(path,method='GET',body){const r=await fetch(path,{method,credentials:'same-origin',cache:'no-store',headers:method==='GET'?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf},...(body?{body:JSON.stringify(body)}:{})});let data;try{data=await r.json();}catch{throw Error('Unexpected server response. Your changes were not confirmed.');}if(!r.ok){if(r.status===401){user=null;$('#hr-workspace').hidden=true;$('#hr-auth').hidden=false;}const e=Error(data.error||'request_failed');e.fields=data.fields||[];throw e;}return data;}
const translations={publication_incomplete:'Complete the publishing fields highlighted below.',version_conflict:'Another editor changed this job. Reload the workspace before making further changes; your current form has been kept.',approval_required:'Confirm the publishing approval checkbox first.',publisher_required:'Only a publishing-authorized HR account can publish or close jobs.',sign_in_required:'Your session expired. Sign in again.',request_not_allowed:'This request could not be authorized. Refresh and sign in again.',invalid_job:'Check the job fields before saving.'};
function handleError(e){editor.querySelectorAll('[aria-invalid]').forEach(n=>n.removeAttribute('aria-invalid'));for(const key of e.fields||[]){if(editor.elements[key]){editor.elements[key].setAttribute('aria-invalid','true');editor.elements[key].closest('details').open=true;}}message((translations[e.message]||e.message)+(e.fields?.length?`\nNeeds attention: ${e.fields.map(k=>$('#hr-'+k)?.closest('label')?.textContent.split('\n')[0]||k).join(', ')}`:''),true);}
async function select(row){selected=row;dirty=false;editor.hidden=false;$('#hr-empty').hidden=true;for(const k of fieldNames)editor.elements[k].value=row?.draft[k]||'';$('#hr-editor-title').textContent=row?.draft.title||'New role';$('#hr-state').textContent=(row?.status||'draft').toUpperCase();$('#hr-reference').textContent=row?`${row.id} · Draft version ${row.version}`:'Reference assigned when saved';$('#hr-approval').checked=false;message(row?.reviewNote||'');renderList();gate();$('#hr-audit').textContent='No recorded changes.';if(row){try{const events=demo?row.events||[]:(await api(`/api/hr/jobs/${row.id}/audit`)).events;$('#hr-audit').innerHTML=events.length?events.map(e=>`<p>${esc(e.action)} · ${esc(e.actor)} · v${e.version} · ${esc(e.at)}</p>`).join(''):'No recorded changes.';}catch{}}}
$('#hr-add').addEventListener('click',()=>{if(canLeave())select(null);});
async function refresh(row){if(demo){const at=jobs.findIndex(j=>j.id===row.id);if(at<0)jobs.unshift(row);else jobs[at]=row;}else jobs=(await api('/api/hr/jobs')).jobs;await select(jobs.find(j=>j.id===row.id));}
function previewIssues(v){const missing=['title','department','entity','workModel','employmentType','summary','responsibilities','requirements','benefits','currency','salaryMin','salaryMax','salaryUnit','expiresAt'].filter(k=>!v[k]);if(v.workModel==='remote'&&!v.eligibleCountries)missing.push('eligibleCountries');if(v.workModel&&v.workModel!=='remote'){if(!v.city)missing.push('city');if(!v.country)missing.push('country');}if(v.expiresAt&&Date.parse(v.expiresAt+'T23:59:59Z')<=Date.now())missing.push('expiresAt');return [...new Set(missing)];}
function demoMutate(action,values){let row=selected?structuredClone(selected):{id:'ald-'+crypto.randomUUID().replaceAll('-','').slice(0,12),version:0,status:'draft',draft:{},live:null,events:[]};if(action==='save'){if(!values.title)throw Object.assign(Error('invalid_job'),{fields:['title']});row.draft=values;}if(action==='publish'){if(!$('#hr-approval').checked)throw Error('approval_required');const issues=previewIssues(row.draft);if(issues.length)throw Object.assign(Error('publication_incomplete'),{fields:issues});row.status='published';row.live={...row.draft,liveVersion:row.version+1};}if(action==='close')row.status='closed';if(action==='duplicate'){row.id='ald-'+crypto.randomUUID().replaceAll('-','').slice(0,12);row.version=0;row.status='draft';row.live=null;row.draft.title+=' (copy)';row.events=[];}row.version++;row.events=[{action,actor:'Review user',version:row.version,at:new Date().toISOString()},...(row.events||[])];return row;}
async function act(action){if(busy)return;if(action==='publish'&&!$('#hr-approval').checked){message('Confirm the publishing approval checkbox first.',true);return;}if(['publish','close'].includes(action)&&!confirm(action==='publish'?`Publish “${selected.draft.title}”? ${demo?'This changes the demo only.':'This will change the public job posting.'}`:`Close “${selected.draft.title}”? ${demo?'This changes the demo only.':'This stops new applications for this role.'}`))return;busy=true;gate();try{let row;if(demo)row=demoMutate(action,formData());else if(action==='save'){row=(await api(selected?`/api/hr/jobs/${selected.id}`:'/api/hr/jobs',selected?'PUT':'POST',selected?{version:selected.version,job:formData()}:{job:formData()})).job;}else row=(await api(`/api/hr/jobs/${selected.id}/${action}`,'POST',{version:selected.version,...(action==='publish'?{approved:true}:{})})).job;await refresh(row);message(`${demo?'Review only: ':''}${({save:'Draft saved. The published version is unchanged.',publish:'Job published.',close:'Job closed. New role-specific applications are blocked.',duplicate:'Copied to a new unpublished draft.'})[action]}`);}catch(e){handleError(e);}finally{busy=false;gate();}}
editor.addEventListener('submit',e=>{e.preventDefault();act('save');});
for(const action of ['publish','close','duplicate'])$('#hr-'+action).addEventListener('click',()=>act(action));
$('#hr-preview').addEventListener('click',()=>{$('#hr-preview-content').innerHTML=roleContent({...formData(),id:selected?.id},{preview:true});$('#hr-preview-dialog').showModal();});
$('#hr-preview-close').addEventListener('click',()=>$('#hr-preview-dialog').close());
$('#hr-logout').addEventListener('click',async()=>{if(!canLeave())return;try{if(!demo)await api('/api/hr/logout','POST',{});dirty=false;location.reload();}catch(e){handleError(e);}});
async function load(){if(demo){const source=await(await fetch('data/careers-openings.json')).json();jobs=source.jobs.map(j=>{const draft=Object.fromEntries(fieldNames.map(k=>[k,j[k]||'']));return{id:j.id,version:1,status:'draft',draft,live:null,reviewNote:j.sourceNote,events:[]};});user={email:'Interactive preview',role:'publisher'};$('#hr-review-banner').hidden=false;$('#hr-logout').textContent='Reset review';}else{const data=await api('/api/hr/session');user=data.user;csrf=user.csrf;jobs=(await api('/api/hr/jobs')).jobs;}$('#hr-auth').hidden=true;$('#hr-workspace').hidden=false;$('#hr-user').textContent=`${user.email} · ${user.role==='publisher'?'Drafting & publishing':'Draft editing only'}`;renderList();if(jobs.length)await select(jobs[0]);}
if(!demo&&allowedReviewHost){$('#hr-login').hidden=true;$('#hr-login-note').textContent='The private HR sign-in is not deployed on this review URL. The interactive review below uses local example state only.';$('#hr-demo-link').hidden=false;}
else load().catch(e=>{$('#hr-login-note').textContent=e.message==='sign_in_required'?'Sign in with an account authorized by Aloden.':'HR sign-in is not available yet. Your developer must activate the protected workspace.';});
