import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {randomUUID,generateKeyPairSync,sign} from 'node:crypto';
import {createJobStore,publicationIssues,cleanJob,JOB_FIELDS} from './jobs-store.mjs';
import {createJobsRouter,renderRole} from './jobs-api.mjs';
import {createHrAuth,createGoogleVerifier} from './hr-auth.mjs';
import {createCareersHandler} from './handler.mjs';
import {buildMime} from './gmail.mjs';
const origin='https://aloden.example';
const fixture=()=>({title:'Synthetic Engineer',department:'software',entity:'Synthetic Employer',workModel:'remote',employmentType:'FULL_TIME',city:'',region:'',country:'',eligibleCountries:'US',summary:'A synthetic job used only in tests.',responsibilities:'Build safe products.\nReview changes.',requirements:'Relevant skills and judgment.',preferred:'Testing experience.',benefits:'Synthetic benefits disclosure.',currency:'USD',salaryMin:'100000',salaryMax:'140000',salaryUnit:'YEAR',expiresAt:new Date(Date.now()+30*86400000).toISOString().slice(0,10),experience:'',joining:'',focus:'',workOn:'',profile:''});
function temporary(t){const dir=mkdtempSync(path.join(tmpdir(),'aloden-jobs-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));return path.join(dir,'jobs.sqlite');}
function storeFor(t){const store=createJobStore(temporary(t));t.after(()=>store.closeDb());return store;}
function publish(store,job=fixture()){const row=store.create(job,'publisher@example.test');return store.publish(row.id,row.version,'publisher@example.test',true);}
const source=()=>JSON.parse(readFileSync('preview/data/careers-openings.json','utf8')).jobs;

test('five exact hiring titles, no invented experience or remuneration',()=>{const jobs=source();assert.deepEqual(jobs.map(j=>j.title),['Senior QA Automation Engineer','Senior Full-Stack Developer','Senior AI/ML Developer','DevOps Cloud Engineer','UI/UX Product Designer']);assert.equal(new Set(jobs.map(j=>j.id)).size,5);assert.equal(jobs[1].experience,'6+ years');assert.equal(jobs[2].experience,'5+ years');for(const j of jobs){assert.equal(j.salaryMin,'');assert.equal(j.salaryMax,'');assert.equal(j.expiresAt,'');}for(const i of [0,3,4]){assert.equal(jobs[i].sourceStatus,'description-draft');assert.equal(jobs[i].experience,'');assert.equal(jobs[i].workModel,'');}});
test('imports create only drafts and never overwrite HR edits',t=>{const store=storeFor(t);const seed=source()[0],input=Object.fromEntries(JOB_FIELDS.map(k=>[k,seed[k]||'']));let r=store.importDraft(seed.id,input,'import');assert.equal(r.status,'draft');assert.equal(store.publicList().length,0);r=store.edit(r.id,r.version,{...r.draft,title:'Changed by HR'},'editor');r=store.importDraft(seed.id,input,'import');assert.equal(r.draft.title,'Changed by HR');});
test('publish requires explicit approval and complete real metadata',t=>{const store=storeFor(t);const r=store.create({title:'Incomplete'},'editor');assert.throws(()=>store.publish(r.id,r.version,'publisher',false),/approval_required/);assert.throws(()=>store.publish(r.id,r.version,'publisher',true),/publication_incomplete/);assert(publicationIssues(cleanJob({title:'Incomplete'})).includes('eligibleCountries')===false);assert.equal(store.publicList().length,0);assert.throws(()=>cleanJob({...fixture(),administrator:true}),/invalid_job/);assert(publicationIssues({...fixture(),salaryMax:'1'}).includes('salaryMax'));assert(publicationIssues({...fixture(),expiresAt:'2099-02-30'}).includes('expiresAt'));});
test('draft edits do not change published data, version or SEO lastmod',t=>{const store=storeFor(t);let r=publish(store);const before=store.publicGet(r.id).job;r=store.edit(r.id,r.version,{...r.draft,title:'Unpublished revision'},'editor');const after=store.publicGet(r.id).job;assert.equal(after.title,before.title);assert.equal(after.version,before.version);assert.equal(after.updatedAt,before.updatedAt);r=store.publish(r.id,r.version,'publisher',true);assert.equal(store.publicGet(r.id).job.title,'Unpublished revision');assert.equal(store.audit(r.id)[0].action,'publish');});
test('stale writes rejected; close hides active list; duplicate is unpublished',t=>{const store=storeFor(t);let r=publish(store);assert.throws(()=>store.edit(r.id,1,r.draft,'editor'),/version_conflict/);const duplicate=store.duplicate(r.id,r.version,'editor');assert.equal(duplicate.status,'draft');assert.equal(duplicate.live,null);r=store.close(r.id,r.version,'publisher');assert.equal(store.publicList().length,0);assert.equal(store.publicGet(r.id).status,410);assert.equal(store.publicGet(duplicate.id).status,404);});
test('expiry stops public access and persists across database restart',t=>{const file=temporary(t);let now=Date.now();let store=createJobStore(file,{now:()=>now});const r=publish(store);store.closeDb();now+=40*86400000;store=createJobStore(file,{now:()=>now});assert.equal(store.publicList().length,0);assert.equal(store.publicGet(r.id).status,410);store.closeDb();});
function router(store,auth){return createJobsRouter({store,auth,origin,templatePath:'preview/career-role.html',careersPath:'preview/careers.html'});}
const req=(url,method='GET',body,headers={})=>new Request(origin+url,{method,headers:{'Content-Type':'application/json',Origin:origin,...headers},...(body?{body:JSON.stringify(body)}:{})});
test('public feed exposes no drafts; SSR has correct metadata; closing removes schema',async t=>{const store=storeFor(t),route=router(store);store.create({title:'SECRET DRAFT'},'editor');const r=publish(store);const list=await(await route(req('/api/careers/jobs'))).json();assert.equal(list.jobs.length,1);assert(!JSON.stringify(list).includes('SECRET DRAFT'));const html=await(await route(req('/jobs/'+r.id))).text();assert(html.includes('<h1>Synthetic Engineer</h1>'));assert(html.includes('"@type":"JobPosting"'));assert(html.includes(`careers.html?job=${r.id}`));assert(html.includes(`<base href="/">`));const careers=await(await route(req('/careers.html'))).text();assert(!careers.includes('REVIEW SNAPSHOT'));assert(careers.includes('Synthetic Engineer'));const site=await(await route(req('/jobs-sitemap.xml'))).text();assert(site.includes(r.id));store.close(r.id,r.version,'publisher');const gone=await route(req('/jobs/'+r.id));assert.equal(gone.status,410);assert(!(await gone.text()).includes('JobPosting'));assert(!(await(await route(req('/jobs-sitemap.xml'))).text()).includes(r.id));});
test('HTML escaping blocks script injection in role body and structured data',()=>{const j={...fixture(),id:'ald-000000000001',title:'<img src=x onerror=alert(1)>',summary:'</script><script>alert(1)</script>',datePosted:new Date().toISOString()};const template=readFileSync('preview/career-role.html','utf8');const html=renderRole(template,j,origin);assert(!html.includes('<img src=x'));assert(!html.includes('</script><script>alert(1)'));assert(html.includes('&lt;img'));const draft=renderRole(template,j,origin,{preview:true});assert(draft.includes('noindex,nofollow'));assert(!draft.includes('JobPosting'));});
test('job manager API requires authentication, authorization and bounded JSON',async t=>{const store=storeFor(t);assert.equal((await router(store)(req('/api/hr/jobs'))).status,503);const auth={authorize(request,publisher){if(!request.headers.get('x-test-user'))throw Object.assign(Error('sign_in_required'),{status:401});if(publisher&&request.headers.get('x-test-user')!=='publisher')throw Object.assign(Error('publisher_required'),{status:403});return {email:'test@example.test'};}};const route=router(store,auth);assert.equal((await route(req('/api/hr/jobs'))).status,401);let created=await route(req('/api/hr/jobs','POST',{job:fixture()},{'x-test-user':'editor'}));assert.equal(created.status,201);const {job}=await created.json();assert.equal((await route(req(`/api/hr/jobs/${job.id}/publish`,'POST',{version:job.version,approved:true},{'x-test-user':'editor'}))).status,403);assert.equal((await route(req(`/api/hr/jobs/${job.id}/publish`,'POST',{version:job.version,approved:true},{'x-test-user':'publisher'}))).status,200);assert.equal((await route(req('/api/hr/jobs','POST',{job:{title:'x'.repeat(40000)}},{'x-test-user':'editor'}))).status,413);});

function application(jobId){const f=new FormData();for(const[k,v]of Object.entries({name:'Synthetic Candidate',email:'test@example.test',interest:'general',location:'Test city',availability:'immediate',consent:'yes',website:'',turnstileToken:'test',jobId}))f.set(k,v);f.set('resume',new Blob(['%PDF-1.7\nTest\n%%EOF'],{type:'application/pdf'}),'test.pdf');return f;}
function appHarness(store,scan){const received=[],ledger=new Map();const s={enabled:true,allowedOrigins:[origin],applicantNoticeUrl:'/privacy.html',turnstileSiteKey:'synthetic-site-key',rateLimit:async()=>({allowed:true}),verifyBot:async()=>true,scanResume:scan||(async()=>({clean:true})),jobs:store,ledger:{reserve(id,fp){const r=ledger.get(id);if(r){if(r.fp!==fp)return {status:'conflict'};return {status:r.status};}ledger.set(id,{fp,status:'processing'});return {status:'reserved'};},mark(id,state){ledger.get(id).status=state;}},deliver:async p=>{received.push({...p,candidate:structuredClone(p.candidate)});return {providerId:'synthetic-receipt'};}};return {received,handle:createCareersHandler(s)};}
async function send(h,id,key=randomUUID()){return h.handle(new Request(origin+'/api/careers/applications',{method:'POST',headers:{Origin:origin,'Idempotency-Key':key},body:application(id)}),{clientKey:'127.0.0.1'});}
test('role-specific application uses server job title/reference and writes them into HR email',async t=>{const s=storeFor(t),r=publish(s),h=appHarness(s);assert.equal((await send(h,r.id)).status,201);const payload=h.received[0];assert.equal(payload.candidate.job.title,r.draft.title);assert.equal(payload.candidate.job.id,r.id);assert.equal(payload.candidate.interest,'Software Engineering');const text=buildMime({...payload,resume:{filename:'resume.pdf',contentType:'application/pdf',bytes:Buffer.from('test')}},'careers@example.test');const part=text.split('Content-Transfer-Encoding: base64\r\n\r\n')[1].split('\r\n\r\n')[0];assert(Buffer.from(part.replaceAll('\r\n',''),'base64').toString().includes('Job reference: '+r.id));});
test('closed/nonexistent/tampered jobs never become general applications',async t=>{const s=storeFor(t),r=publish(s),h=appHarness(s);s.close(r.id,r.version,'publisher');for(const id of [r.id,'ald-ffffffffffff','not-a-job'])assert.equal((await send(h,id)).status,409);assert.equal(h.received.length,0);assert.equal((await send(h,'general')).status,201);assert.equal(h.received[0].candidate.job,null);});
test('job closed during scan is rejected; already accepted retry does not resend',async t=>{const s=storeFor(t),r=publish(s),h=appHarness(s,async()=>{s.close(r.id,r.version,'publisher');return {clean:true};});assert.equal((await send(h,r.id)).status,409);assert.equal(h.received.length,0);const r2=publish(s),h2=appHarness(s),key=randomUUID();assert.equal((await send(h2,r2.id,key)).status,201);s.close(r2.id,r2.version,'publisher');assert.equal((await send(h2,r2.id,key)).status,200);assert.equal(h2.received.length,1);});

const keys=generateKeyPairSync('rsa',{modulusLength:2048});
const jwk={...keys.publicKey.export({format:'jwk'}),kid:'test-key',use:'sig'};
function jwt(claims){const h=Buffer.from(JSON.stringify({alg:'RS256',kid:jwk.kid})).toString('base64url'),p=Buffer.from(JSON.stringify(claims)).toString('base64url');return `${h}.${p}.${sign('RSA-SHA256',Buffer.from(h+'.'+p),keys.privateKey).toString('base64url')}`;}
const claims=(nonce)=>({iss:'https://accounts.google.com',aud:'client',exp:Math.floor(Date.now()/1000)+300,iat:Math.floor(Date.now()/1000),nonce,sub:'synthetic-sub',email:'publisher@example.test',email_verified:true});
test('Google token verifier rejects wrong audience/issuer/expiry/nonce/verification/signature',async()=>{const verify=createGoogleVerifier({clientId:'client',fetchImpl:async()=>new Response(JSON.stringify({keys:[jwk]}))});assert.equal((await verify(jwt(claims('nonce')),'nonce')).email,'publisher@example.test');for(const change of [{aud:'other'},{iss:'evil'},{exp:0},{email_verified:false},{nonce:'other'},{iat:0}])await assert.rejects(verify(jwt({...claims('nonce'),...change}),'nonce'));await assert.rejects(verify(jwt(claims('nonce'))+'bad','nonce'));});
test('Google login has state/PKCE/cookie binding, exact allowlist, secure sessions and CSRF',async t=>{let expectedNonce='',exchange=0,now=Date.now();const users={'publisher@example.test':'publisher'};const auth=createHrAuth({filename:temporary(t),origin,clientId:'client',clientSecret:'secret',users,now:()=>now,fetchImpl:async url=>{if(url.includes('/certs'))return new Response(JSON.stringify({keys:[jwk]}));exchange++;return new Response(JSON.stringify({id_token:jwt(claims(expectedNonce))}));}});t.after(()=>auth.close());const login=await auth.route(req('/auth/careers/login'),{clientKey:'test'});const u=new URL(login.headers.get('location'));expectedNonce=u.searchParams.get('nonce');assert.equal(u.searchParams.get('code_challenge_method'),'S256');assert.equal(u.searchParams.get('scope'),'openid email');const binding=login.headers.get('set-cookie').split(';')[0];const callback=`/auth/careers/callback?state=${u.searchParams.get('state')}&code=test-code`;
 await auth.route(req(callback));assert.equal(exchange,0,'Cookie binding required before token exchange');const accepted=await auth.route(req(callback,'GET',null,{Cookie:binding}));assert.equal(exchange,1);const cookie=accepted.headers.get('set-cookie');assert(cookie.includes('Secure; HttpOnly; SameSite=Strict'));const cookieHeader=cookie.split(';')[0];const session=(await(await auth.route(req('/api/hr/session','GET',null,{Cookie:cookieHeader}))).json()).user;assert.equal(session.role,'publisher');assert.throws(()=>auth.authorize(req('/api/hr/jobs','POST',{}, {Cookie:cookieHeader})),/request_not_allowed/);assert.throws(()=>auth.authorize(req('/api/hr/jobs','POST',{}, {Cookie:cookieHeader,Origin:'https://evil.test','X-CSRF-Token':session.csrf})),/request_not_allowed/);assert.equal(auth.authorize(req('/api/hr/jobs','POST',{}, {Cookie:cookieHeader,'X-CSRF-Token':session.csrf}),true).role,'publisher');users['publisher@example.test']='editor';assert.throws(()=>auth.authorize(req('/api/hr/jobs','POST',{}, {Cookie:cookieHeader,'X-CSRF-Token':session.csrf}),true),/publisher_required/);await auth.route(req(callback,'GET',null,{Cookie:binding}));assert.equal(exchange,1,'State cannot be replayed');now+=31*60000;assert.equal(auth.session(req('/api/hr/session','GET',null,{Cookie:cookieHeader})),null);});
